bf16: true
cutoff_len: 8192
dataloader_num_workers: 8
dataset: yuancang_train
#deepspeed: disabled - using single GPU train
do_train: true
finetuning_type: full
flash_attn: auto
gradient_accumulation_steps: 8
gradient_checkpointing: true
learning_rate: 1.5e-05
logging_steps: 5
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: null
model_name_or_path: /home/dja/桌面/远苍/Qwen2.5-Math-7B
num_train_epochs: 2
output_dir: /home/dja/桌面/远苍/saves/yuancang-full-sft
overwrite_output_dir: true
per_device_train_batch_size: 2
preprocessing_num_workers: 64
report_to: []
save_steps: 200
stage: sft
template: qwen
trust_remote_code: true
warmup_ratio: 0.1
weight_decay: 0.01
